@extends('layouts.app')
@section('title','Centro de Costos')
@section('content')
<div class="breadcrumb">COSTOS › Centro de Costos</div>
<div class="heading"><div><h1>Centro de Costos</h1><p>Organiza los costos por grupos y centros dependientes.</p></div><div class="heading-actions"><button class="primary" type="button" onclick="document.getElementById('new-cost-parent').showModal()">＋ Nuevo grupo</button></div></div>

<div class="stats"><article><span>▤</span><div><small>Grupos principales</small><strong>{{ $parents->count() }}</strong></div></article><article><span>◫</span><div><small>Centros registrados</small><strong>{{ $parents->sum(fn ($parent) => $parent->children->count()) }}</strong></div></article><article><span>✓</span><div><small>Activos</small><strong>{{ $parents->count() + $parents->sum(fn ($parent) => $parent->children->count()) }}</strong></div></article><article><span>⊘</span><div><small>Retirados</small><strong>{{ $inactive }}</strong></div></article></div>

<div class="card cost-centers-card"><div class="card-title"><div><h2>Grupos de costos</h2><p>Cada grupo puede contener varios centros de costo.</p></div><span class="item-count">{{ $parents->count() }} grupo(s)</span></div>
    <div class="cost-center-tree">@forelse($parents as $parent)
        <section class="cost-parent"><header><div class="cost-parent-icon">▦</div><div><strong>{{ $parent->name }}</strong><small>{{ $parent->code ?: 'Sin código' }} · {{ $parent->children->count() }} centro(s)</small></div><div class="cost-parent-actions"><button type="button" title="Agregar centro" onclick="openCostChild({{ $parent->id }}, @js($parent->name))">＋ Agregar centro</button><button type="button" title="Editar grupo" onclick="openCostEdit({{ $parent->id }}, @js($parent->name), @js($parent->code), @js($parent->description))">Editar</button><form method="post" action="{{ route('cost-centers.destroy',$parent) }}" onsubmit="return confirm('¿Retirar el grupo y sus centros hijos?')">@csrf @method('delete')<button class="danger-link">Retirar</button></form></div></header>
            <div class="cost-children">@forelse($parent->children as $child)<div class="cost-child"><span class="cost-branch">└</span><div><strong>{{ $child->name }}</strong><small>{{ $child->code ?: 'Sin código' }}{{ $child->description ? ' · '.$child->description : '' }}</small></div><div class="cost-child-actions"><button type="button" onclick="openCostEdit({{ $child->id }}, @js($child->name), @js($child->code), @js($child->description))">Editar</button><form method="post" action="{{ route('cost-centers.destroy',$child) }}" onsubmit="return confirm('¿Retirar este centro de costos?')">@csrf @method('delete')<button class="danger-link">Retirar</button></form></div></div>@empty<div class="cost-empty">Aún no hay centros dentro de este grupo. Usa “Agregar centro” para crear el primero.</div>@endforelse</div>
        </section>
    @empty <div class="empty-state"><b>▦</b><p>No hay grupos de costos registrados.</p></div>@endforelse</div>
</div>

<dialog id="new-cost-parent"><div class="modal-head"><div><h2>Nuevo grupo de costos</h2><p>Crea un grupo principal para organizar sus centros hijos. El código se asigna automáticamente.</p></div><button type="button" data-close>×</button></div><form method="post" action="{{ route('cost-centers.store') }}">@csrf <div class="form-grid"><label>Nombre del grupo *<input name="name" required maxlength="150" placeholder="Ej.: GASTOS COMERCIALES"></label><label class="span-2">Descripción<textarea name="description" maxlength="500" placeholder="Descripción opcional"></textarea></label></div><div class="modal-foot"><button type="button" data-close>Cancelar</button><button class="primary">Guardar grupo</button></div></form></dialog>

<dialog id="new-cost-child"><div class="modal-head"><div><h2>Nuevo centro de costos</h2><p id="cost-child-group">Selecciona el grupo al que pertenecerá.</p></div><button type="button" data-close>×</button></div><form method="post" action="{{ route('cost-centers.store') }}">@csrf <input type="hidden" name="parent_id" id="cost-child-parent"><div class="form-grid"><label>Nombre del centro *<input name="name" required maxlength="150" placeholder="Ej.: MANTENIMIENTO DE FLOTA"></label><label class="span-2">Descripción<textarea name="description" maxlength="500" placeholder="Descripción opcional"></textarea></label></div><div class="modal-foot"><button type="button" data-close>Cancelar</button><button class="primary">Guardar centro</button></div></form></dialog>

<dialog id="edit-cost-center"><div class="modal-head"><div><h2>Editar centro de costos</h2><p>Actualiza el nombre o la descripción.</p></div><button type="button" data-close>×</button></div><form method="post" id="edit-cost-form">@csrf @method('put')<div class="form-grid"><label>Nombre *<input name="name" id="edit-cost-name" required maxlength="150"></label><label class="span-2">Descripción<textarea name="description" id="edit-cost-description" maxlength="500"></textarea></label></div><div class="modal-foot"><button type="button" data-close>Cancelar</button><button class="primary">Guardar cambios</button></div></form></dialog>
@endsection
@push('scripts')
<script>
const openCostChild = (id, name) => { document.getElementById('cost-child-parent').value=id; document.getElementById('cost-child-group').textContent=`Se agregará dentro de: ${name}.`; document.getElementById('new-cost-child').showModal(); };
const openCostEdit = (id, name, code, description) => { const form=document.getElementById('edit-cost-form'); form.action=`{{ url('/costos/centro-costos') }}/${id}`; document.getElementById('edit-cost-name').value=name||''; document.getElementById('edit-cost-description').value=description||''; document.getElementById('edit-cost-center').showModal(); };
</script>
@endpush
