@extends('layouts.app')
@section('title','Inventario')
@section('content')
@php
    $totalUnits = $stocks->sum(fn($stock)=>(float)$stock->quantity);
    $totalValue = $stocks->sum(fn($stock)=>(float)$stock->quantity*(float)($stock->product->price ?? 0));
@endphp
<div class="breadcrumb">ALMACÉN › Inventario</div>
<div class="heading"><div><h1>Inventario</h1><p>Consulta existencias, movimientos y kardex; realiza traslados y devoluciones a proveedores.</p></div>@if($tab==='movimientos')<button class="primary" type="button" onclick="document.getElementById('inventory-transfer').showModal()">⇄ Nuevo traslado</button>@elseif($tab==='devoluciones')<button class="primary" type="button" onclick="document.getElementById('supplier-return').showModal()">＋ Nueva devolución</button>@endif</div>
<div class="stats inventory-stats"><article><span>▦</span><div><small>Almacenes activos</small><strong>{{ $warehouses->count() }}</strong></div></article><article><span>◈</span><div><small>Productos con stock</small><strong>{{ $stocks->pluck('product_id')->unique()->count() }}</strong></div></article><article><span>Σ</span><div><small>Unidades disponibles</small><strong>{{ number_format($totalUnits,0) }}</strong></div></article><article><span>S/</span><div><small>Valor de compra</small><strong>{{ number_format($totalValue,2) }}</strong></div></article></div>

<nav class="inventory-tabs" aria-label="Opciones de inventario">
    <a class="{{ $tab==='movimientos'?'active':'' }}" href="{{ route('inventory.index',['tab'=>'movimientos']) }}"><span>⇅</span><b>Movimientos</b><small>Entradas y traslados</small></a>
    <a class="{{ $tab==='kardex'?'active':'' }}" href="{{ route('inventory.index',['tab'=>'kardex']) }}"><span>▤</span><b>Reporte kardex</b><small>Historial por producto</small></a>
    <a class="{{ $tab==='inventario'?'active':'' }}" href="{{ route('inventory.index',['tab'=>'inventario']) }}"><span>▦</span><b>Reporte inventario</b><small>Stock por almacén</small></a>
    <a class="{{ $tab==='devoluciones'?'active':'' }}" href="{{ route('inventory.index',['tab'=>'devoluciones']) }}"><span>↩</span><b>Devolución a proveedor</b><small>Documentos de salida</small></a>
</nav>

@if(in_array($tab,['kardex','inventario']))
<form class="inventory-filters" method="get"><input type="hidden" name="tab" value="{{ $tab }}"><label>Producto<select name="product_id"><option value="">Todos los productos</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected(request('product_id')==$product->id)>{{ $product->code }} · {{ $product->name }}</option>@endforeach</select></label><label>Almacén<select name="warehouse_id"><option value="">Todos los almacenes</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected(request('warehouse_id')==$warehouse->id)>{{ $warehouse->name }}</option>@endforeach</select></label>@if($tab==='kardex')<label>Desde<input type="date" name="date_from" value="{{ request('date_from') }}"></label><label>Hasta<input type="date" name="date_to" value="{{ request('date_to') }}"></label>@endif<button class="secondary">Filtrar</button><a href="{{ route('inventory.index',['tab'=>$tab]) }}">Limpiar</a></form>
@endif

@if($tab==='movimientos')
<div class="card inventory-card inventory-products-card"><div class="card-title"><div><h2>Productos en almacén</h2><p>Listado de productos asignados a cada almacén, incluyendo aquellos que actualmente tienen stock cero.</p></div></div><div class="table-wrap"><table><thead><tr><th>Producto</th><th>Almacén</th><th>Stock</th><th>Unidad de medida</th></tr></thead><tbody>@forelse($warehouseProducts as $stock)<tr><td><strong>{{ $stock->product->code }} · {{ $stock->product->name }}</strong><small>{{ $stock->product->category }}</small></td><td><strong>{{ $stock->warehouse->name }}</strong><small>{{ $stock->warehouse->branch?->name ?? 'Sin sucursal' }}</small></td><td><strong class="inventory-stock-number">{{ number_format($stock->quantity,0) }}</strong></td><td>{{ $stock->product->unit }}</td></tr>@empty<tr><td colspan="4"><div class="empty-state"><b>▦</b><p>No hay productos asignados a almacenes.</p></div></td></tr>@endforelse</tbody></table></div></div>
<div class="card inventory-card inventory-history-card"><div class="card-title"><div><h2>Historial de movimientos</h2><p>Recepciones, traslados y salidas registradas en los almacenes.</p></div></div><div class="table-wrap"><table><thead><tr><th>Documento</th><th>Fecha</th><th>Movimiento</th><th>Producto</th><th>Origen</th><th>Destino</th><th>Cantidad</th><th>Referencia / responsable</th></tr></thead><tbody>@forelse($movements as $movement)<tr><td><code>{{ $movement->code }}</code></td><td>{{ $movement->occurred_at->format('d/m/Y H:i') }}</td><td><span class="inventory-badge {{ str($movement->type)->slug() }}">{{ $movement->type }}</span></td><td><strong>{{ $movement->product->name }}</strong><small>{{ $movement->product->code }} · {{ $movement->product->unit }}</small></td><td>{{ $movement->sourceWarehouse?->name ?? '—' }}</td><td>{{ $movement->destinationWarehouse?->name ?? '—' }}</td><td><strong>{{ number_format($movement->quantity,0) }}</strong> {{ $movement->product->unit }}</td><td>{{ $movement->reference ?? '—' }}<small>{{ $movement->creator?->name ?? 'Sistema' }}</small></td></tr>@empty<tr><td colspan="8"><div class="empty-state"><b>⇅</b><p>Aún no hay movimientos registrados.</p></div></td></tr>@endforelse</tbody></table></div>@if($movements->hasPages())<div class="pagination-wrap">{{ $movements->links() }}</div>@endif</div>
@elseif($tab==='kardex')
<div class="card inventory-card"><div class="card-title"><div><h2>Kardex de productos</h2><p>Entradas, traslados y salidas ordenadas cronológicamente.</p></div></div><div class="table-wrap"><table><thead><tr><th>Documento</th><th>Fecha</th><th>Movimiento</th><th>Producto</th><th>Origen</th><th>Destino</th><th>Cantidad</th><th>Referencia / responsable</th></tr></thead><tbody>@forelse($movements as $movement)<tr><td><code>{{ $movement->code }}</code></td><td>{{ $movement->occurred_at->format('d/m/Y H:i') }}</td><td><span class="inventory-badge {{ str($movement->type)->slug() }}">{{ $movement->type }}</span></td><td><strong>{{ $movement->product->name }}</strong><small>{{ $movement->product->code }} · {{ $movement->product->unit }}</small></td><td>{{ $movement->sourceWarehouse?->name ?? '—' }}</td><td>{{ $movement->destinationWarehouse?->name ?? '—' }}</td><td><strong>{{ number_format($movement->quantity,0) }}</strong> {{ $movement->product->unit }}</td><td>{{ $movement->reference ?? '—' }}<small>{{ $movement->creator?->name ?? 'Sistema' }}</small></td></tr>@empty<tr><td colspan="8"><div class="empty-state"><b>▤</b><p>No hay movimientos para los filtros seleccionados.</p></div></td></tr>@endforelse</tbody></table></div>@if($movements->hasPages())<div class="pagination-wrap">{{ $movements->links() }}</div>@endif</div>
@elseif($tab==='inventario')
<div class="card inventory-card"><div class="card-title"><div><h2>Existencias por almacén</h2><p>Las cantidades reflejan las recepciones, traslados y devoluciones registradas.</p></div></div><div class="table-wrap"><table><thead><tr><th>Sucursal</th><th>Almacén</th><th>Código</th><th>Producto</th><th>Unidad</th><th>Stock disponible</th><th>Stock mínimo</th><th>Valor referencial</th></tr></thead><tbody>@forelse($stocks as $stock)<tr><td>{{ $stock->warehouse->branch?->name ?? '—' }}</td><td><strong>{{ $stock->warehouse->name }}</strong></td><td><code>{{ $stock->product->code }}</code></td><td>{{ $stock->product->name }}</td><td>{{ $stock->product->unit }}</td><td><strong>{{ number_format($stock->quantity,0) }}</strong></td><td>{{ number_format($stock->product->min_stock,0) }}</td><td>S/ {{ number_format((float)$stock->quantity*(float)$stock->product->price,2) }}</td></tr>@empty<tr><td colspan="8"><div class="empty-state"><b>▦</b><p>No hay existencias para los filtros seleccionados.</p></div></td></tr>@endforelse</tbody></table></div></div>
@else
<div class="card inventory-card"><div class="card-title"><div><h2>Documentos de devolución</h2><p>Cada documento descuenta el stock del almacén y mantiene trazabilidad del proveedor.</p></div></div><div class="table-wrap"><table><thead><tr><th>Documento</th><th>Fecha</th><th>Proveedor</th><th>Producto</th><th>Almacén</th><th>Cantidad</th><th>Referencia</th><th>Responsable</th></tr></thead><tbody>@forelse($returns as $return)<tr><td><code>{{ $return->code }}</code></td><td>{{ $return->occurred_at->format('d/m/Y') }}</td><td>{{ $return->supplier?->name ?? '—' }}</td><td><strong>{{ $return->product->name }}</strong><small>{{ $return->product->code }}</small></td><td>{{ $return->sourceWarehouse?->name ?? '—' }}</td><td><strong>{{ number_format($return->quantity,0) }}</strong> {{ $return->product->unit }}</td><td>{{ $return->reference }}</td><td>{{ $return->creator?->name ?? 'Sistema' }}</td></tr>@empty<tr><td colspan="8"><div class="empty-state"><b>↩</b><p>No se han emitido devoluciones a proveedores.</p></div></td></tr>@endforelse</tbody></table></div>@if($returns->hasPages())<div class="pagination-wrap">{{ $returns->links() }}</div>@endif</div>
@endif

<dialog id="inventory-transfer" class="inventory-dialog"><div class="modal-head"><div><h2>Traslado entre almacenes</h2><p>El stock total no cambia; las existencias pasan del origen al destino.</p></div><button type="button" data-close>×</button></div><form method="post" action="{{ route('inventory.transfers.store') }}">@csrf<div class="inventory-form"><label>Fecha *<input type="date" name="occurred_at" value="{{ old('occurred_at',now()->format('Y-m-d')) }}" required></label><label class="span-2">Producto *<select name="product_id" required><option value="">Seleccionar</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->code }} · {{ $product->name }}</option>@endforeach</select></label><label>Almacén origen *<select name="source_warehouse_id" required><option value="">Seleccionar</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select></label><label>Almacén destino *<select name="destination_warehouse_id" required><option value="">Seleccionar</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select></label><label>Cantidad *<input type="number" name="quantity" min="1" step="1" required></label><label class="span-3">Observaciones<textarea name="notes" rows="3"></textarea></label></div><div class="modal-foot"><button type="button" data-close>Cancelar</button><button class="primary">Registrar traslado</button></div></form></dialog>
<dialog id="supplier-return" class="inventory-dialog"><div class="modal-head"><div><h2>Nueva devolución a proveedor</h2><p>Se generará automáticamente un documento DEV y se descontará el stock.</p></div><button type="button" data-close>×</button></div><form method="post" action="{{ route('inventory.returns.store') }}">@csrf<div class="inventory-form"><label>Fecha *<input type="date" name="occurred_at" value="{{ old('occurred_at',now()->format('Y-m-d')) }}" required></label><label class="span-2">Proveedor *<select name="supplier_id" required><option value="">Seleccionar proveedor</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->document_number }} · {{ $supplier->name }}</option>@endforeach</select></label><label class="span-2">Producto *<select name="product_id" required><option value="">Seleccionar producto</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->code }} · {{ $product->name }}</option>@endforeach</select></label><label>Almacén *<select name="source_warehouse_id" required><option value="">Seleccionar</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select></label><label>Cantidad *<input type="number" name="quantity" min="1" step="1" required></label><label class="span-2">Referencia del proveedor *<input name="reference" maxlength="150" placeholder="Guía, factura o motivo" required></label><label class="span-3">Observaciones<textarea name="notes" rows="3"></textarea></label></div><div class="modal-foot"><button type="button" data-close>Cancelar</button><button class="primary">Emitir devolución</button></div></form></dialog>
@endsection
