@extends('layouts.app')
@section('title','Cotizaciones')
@section('content')
<div class="breadcrumb">LOGÍSTICA › Cotizaciones</div><div class="heading"><div><h1>Cotizaciones de requerimientos</h1><p>Cada requerimiento aprobado requiere al menos tres proveedores y una cotización ganadora antes de pasar a aprobación.</p></div></div>
<div class="stats"><article><span>▧</span><div><small>Requerimientos aprobados</small><strong>{{ $requirements->total() }}</strong></div></article><article><span>⌛</span><div><small>Pendientes de cotizar</small><strong>{{ $requirements->getCollection()->filter(fn($r)=>!$r->quotationProcess)->count() }}</strong></div></article><article><span>◷</span><div><small>En aprobación</small><strong>{{ $requirements->getCollection()->filter(fn($r)=>$r->quotationProcess?->status==='Pendiente aprobación')->count() }}</strong></div></article><article><span>✓</span><div><small>Aprobadas</small><strong>{{ $requirements->getCollection()->filter(fn($r)=>$r->quotationProcess?->status==='Aprobada')->count() }}</strong></div></article></div>
<div class="quotation-flow-list">@forelse($requirements as $requirement)@php($process=$requirement->quotationProcess)
<article class="quotation-flow-card"><header><div><code>{{ $requirement->code }}</code><h2>{{ $requirement->project }}</h2><p>{{ $requirement->responsible }} · {{ $requirement->items->count() }} ítem(s) · {{ $requirement->requested_at->format('d/m/Y') }}</p></div><span class="badge {{ $process?->status==='Aprobada'?'aprobado':($process?->status==='Rechazada'?'rechazado':'pendiente') }}">{{ $process?->status ?? 'Pendiente cotización' }}</span></header>
@if($process?->status==='Rechazada')<div class="quotation-rejection"><strong>Observación de aprobación</strong><p>{{ $process->approval_observation }}</p><small>Corrige las propuestas, vuelve a adjuntar mínimo tres cotizaciones y selecciona nuevamente al ganador.</small></div>@endif
@if($process && $process->quotations->isNotEmpty())<div class="quotation-files">@foreach($process->quotations as $quote)<a target="_blank" class="{{ $quote->is_winner?'winner':'' }}" href="{{ route('quotations.show',$quote) }}"><span>{{ $quote->is_winner?'★':'▧' }}</span><div><strong>{{ $quote->supplier->name }}</strong><small>{{ $quote->original_name }}{{ $quote->amount!==null?' · '.$quote->currency.' '.number_format($quote->amount,2):'' }}</small></div>@if($quote->is_winner)<b>GANADORA</b>@endif</a>@endforeach</div>@endif
<div class="process-actions">@if(!$process || $process->status==='Rechazada')<button class="primary" type="button" onclick="document.getElementById('quote-{{ $requirement->id }}').showModal()">{{ $process?'↻ Volver a cotizar':'＋ Registrar cotizaciones' }}</button>@elseif($process->status==='Pendiente aprobación')<small class="quotation-waiting">Enviado a aprobación · versión {{ $process->version }}</small>@else<small class="quotation-waiting approved">Cotización ganadora aprobada y disponible para la orden de compra.</small>@endif @if(auth()->user()->isAdministrator() && $process)<form method="post" action="{{ route('quotations.destroy',$process) }}" onsubmit="return confirm('¿Eliminar definitivamente este proceso de cotización y sus archivos?')">@csrf @method('DELETE')<button class="danger">Eliminar</button></form>@endif</div>
</article>
@if(!$process || $process->status==='Rechazada')
<dialog class="quotation-dialog" id="quote-{{ $requirement->id }}"><div class="modal-head"><div><h2>Cotizaciones · {{ $requirement->code }}</h2><p>Revisa el contenido solicitado, registra tres proveedores distintos y marca al ganador.</p></div><button type="button" data-close>×</button></div><form method="post" enctype="multipart/form-data" action="{{ route('quotations.store',$requirement) }}">@csrf
<section class="quotation-requirement-detail"><h3>Contenido del requerimiento</h3><div class="table-wrap"><table><thead><tr><th>#</th><th>Producto o servicio</th><th>Descripción</th><th>Cantidad requerida</th><th>Cantidad aprobada</th><th>Unidad</th></tr></thead><tbody>@foreach($requirement->items as $index=>$item)<tr><td>{{ $index+1 }}</td><td><strong>{{ $item->product_name }}</strong></td><td>{{ $item->description ?: '—' }}</td><td>{{ rtrim(rtrim(number_format((float)$item->quantity,2,'.',''),'0'),'.') }}</td><td><strong>{{ rtrim(rtrim(number_format((float)($item->approved_quantity ?? $item->quantity),2,'.',''),'0'),'.') }}</strong></td><td>{{ $item->unit }}</td></tr>@endforeach</tbody></table></div></section>
<datalist id="registered-suppliers">@foreach($suppliers as $supplier)<option value="{{ $supplier->document_number }} · {{ $supplier->name }}"></option>@endforeach</datalist><div class="quotation-entry-head"><span>Proveedor relacionado</span><span>Archivo</span><span>Monto</span><span>Moneda</span><span>Ganador</span></div><div class="quotation-entry-list">@for($i=0;$i<3;$i++)<div class="quotation-entry"><span class="quotation-supplier-field"><input type="text" list="registered-suppliers" name="quotes[{{ $i }}][supplier_label]" placeholder="RUC o nombre del proveedor {{ $i+1 }}" autocomplete="off" required><button type="button" class="open-quotation-supplier" title="Crear en Clientes y Proveedores">＋</button></span><input type="file" name="quotes[{{ $i }}][file]" accept="application/pdf,image/jpeg,image/png,image/webp" required><input type="number" step="0.01" min="0" name="quotes[{{ $i }}][amount]" placeholder="Opcional"><select name="quotes[{{ $i }}][currency]"><option value="PEN">PEN</option><option value="USD">USD</option></select><label class="quote-winner-check"><input type="radio" name="winner_index" value="{{ $i }}" required><span>★ Ganador</span></label></div>@endfor</div>
<div class="modal-foot"><small>Selecciona exactamente un proveedor ganador antes de enviar.</small><button type="button" data-close>Cancelar</button><button class="primary">Enviar a aprobación</button></div></form></dialog>
@endif
@empty<div class="empty-state"><b>▧</b><p>No hay requerimientos aprobados para cotizar.</p></div>@endforelse</div>{{ $requirements->links() }}
<dialog id="new-quotation-supplier"><div class="modal-head"><div><h2>Nuevo proveedor</h2><p>Se guardará directamente en Clientes y Proveedores y quedará seleccionado en la cotización.</p></div><button type="button" data-close>×</button></div><form id="new-quotation-supplier-form" method="post" action="{{ route('purchase-orders.suppliers.store') }}">@csrf<div class="form-grid"><label>RUC *<input name="document_number" inputmode="numeric" maxlength="11" required></label><label>Razón social *<input name="name" required></label><label>Teléfono<input name="phone"></label><label>Correo<input name="email" type="email"></label></div><div class="modal-foot"><a class="secondary" href="{{ route('business-partners.index') }}">Abrir Clientes y Proveedores</a><button type="button" data-close>Cancelar</button><button class="primary">Crear y seleccionar</button></div></form></dialog>
@endsection
@push('scripts')<script>(()=>{const dialog=document.getElementById('new-quotation-supplier'),form=document.getElementById('new-quotation-supplier-form'),list=document.getElementById('registered-suppliers');let target=null;document.querySelectorAll('.open-quotation-supplier').forEach(button=>button.addEventListener('click',()=>{target=button.previousElementSibling;dialog.showModal();}));form.addEventListener('submit',async event=>{event.preventDefault();try{const response=await fetch(form.action,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':@json(csrf_token())},body:new FormData(form)});const body=await response.json();if(!response.ok)throw new Error(body.message||Object.values(body.errors||{}).flat()[0]||'No se pudo crear el proveedor.');const label=`${body.document_number} · ${body.name}`;const option=document.createElement('option');option.value=label;list.appendChild(option);if(target)target.value=label;form.reset();dialog.close();}catch(error){alert(error.message);}});})();</script>@endpush
