@extends('layouts.app')
@section('title','Cotizaciones')
@section('content')
<div class="breadcrumb">LOGÍSTICA › Cotizaciones</div>
<div class="heading"><div><h1>Cotizaciones por bloque</h1><p>Selecciona requerimientos completos o ítems aprobados para cotizar en un solo bloque.</p></div><button class="primary" type="button" id="open-quotation-block" disabled>＋ Crear bloque de cotización</button></div>
<div class="stats"><article><span>▤</span><div><small>Requerimientos disponibles</small><strong>{{ $requirements->count() }}</strong></div></article><article><span>✓</span><div><small>Ítems aprobados</small><strong>{{ $availableItems->count() }}</strong></div></article><article><span>◷</span><div><small>En aprobación</small><strong>{{ $processes->getCollection()->where('status','Pendiente aprobación')->count() }}</strong></div></article><article><span>★</span><div><small>Bloques aprobados</small><strong>{{ $processes->getCollection()->where('status','Aprobada')->count() }}</strong></div></article></div>

<div class="card approval-items-board"><header><div><h2>Ítems aprobados para cotizar</h2><p>Marca un requerimiento completo o los productos y servicios específicos.</p></div><span class="badge aprobado" id="selected-item-count">0 ítems seleccionados</span></header><form method="post" enctype="multipart/form-data" action="{{ route('quotations.blocks.store') }}" id="quotation-selection-form">@csrf
<div class="table-wrap"><table><thead><tr><th><input type="checkbox" id="select-all-quotation-items"></th><th>Requerimiento / proyecto</th><th>Producto o servicio</th><th>Cantidad aprobada</th><th>Centro de costo</th><th>Estado</th></tr></thead><tbody>
@forelse($requirements as $requirementId => $items)
    @php($requirement = $items->first()->requirement)
    @foreach($items as $index => $item)<tr><td><input type="checkbox" class="quotation-item-check requirement-{{ $requirementId }}" name="item_ids[]" value="{{ $item->id }}"></td>@if($index === 0)<td rowspan="{{ $items->count() }}"><label class="check"><input type="checkbox" class="quotation-requirement-check" data-requirement="{{ $requirementId }}"> <strong>{{ $requirement->code }}</strong></label><small>{{ $requirement->project }} · {{ $requirement->area }}</small></td>@endif<td><strong>{{ $item->product_name }}</strong>@if($item->description)<small>{{ $item->description }}</small>@endif</td><td>{{ rtrim(rtrim(number_format((float)($item->approved_quantity ?? $item->quantity),2,'.',''),'0'),'.') }} {{ $item->unit }}</td><td>{{ $item->cost_center ?: '—' }}</td><td><span class="badge aprobado">{{ $item->approval_status }}</span></td></tr>@endforeach
@empty<tr><td colspan="6"><div class="empty-state"><b>✓</b><p>No hay ítems con aprobación final disponibles para cotizar.</p></div></td></tr>@endforelse
</tbody></table></div>
<dialog class="quotation-dialog" id="quotation-block-dialog"><div class="modal-head"><div><h2>Nuevo bloque de cotización</h2><p id="quotation-block-summary">Los ítems seleccionados serán evaluados por los proveedores.</p></div><button type="button" data-close>×</button></div><section class="quotation-requirement-detail"><h3>Ítems incluidos</h3><ul id="quotation-selected-items"></ul></section><datalist id="registered-suppliers">@foreach($suppliers as $supplier)<option value="{{ $supplier->document_number }} · {{ $supplier->name }}"></option>@endforeach</datalist><div class="quotation-entry-head"><span>Proveedor</span><span>Archivo</span><span>Monto</span><span>Moneda</span><span>Ganador</span></div><div class="quotation-entry-list">@for($i=0;$i<3;$i++)<div class="quotation-entry"><input type="text" list="registered-suppliers" name="quotes[{{ $i }}][supplier_label]" placeholder="RUC o proveedor {{ $i+1 }}" required><input type="file" name="quotes[{{ $i }}][file]" accept="application/pdf,image/jpeg,image/png,image/webp" required><input type="number" step="0.01" min="0" name="quotes[{{ $i }}][amount]" placeholder="Opcional"><select name="quotes[{{ $i }}][currency]"><option value="PEN">PEN</option><option value="USD">USD</option></select><label class="quote-winner-check"><input type="radio" name="winner_index" value="{{ $i }}" required><span>★ Ganador</span></label></div>@endfor</div><div class="modal-foot"><small>Registra tres proveedores distintos y selecciona un ganador.</small><button type="button" data-close>Cancelar</button><button class="primary">Enviar a aprobación</button></div></dialog></form></div>

<div class="heading"><div><h2>Bloques registrados</h2><p>Historial de cotizaciones enviadas a aprobación.</p></div></div><div class="quotation-flow-list">@forelse($processes as $process)<article class="quotation-flow-card"><header><div><code>{{ $process->block_code ?: 'COT-'.str_pad((string)$process->id,4,'0',STR_PAD_LEFT) }}</code><h2>{{ $process->items->count() }} ítem(s) cotizados</h2><p>{{ $process->items->pluck('requirement.code')->unique()->implode(' · ') }}</p></div><span class="badge {{ $process->status==='Aprobada'?'aprobado':($process->status==='Rechazada'?'rechazado':'pendiente') }}">{{ $process->status }}</span></header><ul>@foreach($process->items as $item)<li><strong>{{ $item->product_name }}</strong> · {{ $item->requirement?->code }}</li>@endforeach</ul><div class="quotation-files">@foreach($process->quotations as $quote)<a target="_blank" class="{{ $quote->is_winner?'winner':'' }}" href="{{ route('quotations.show',$quote) }}"><span>{{ $quote->is_winner?'★':'▧' }}</span><div><strong>{{ $quote->supplier->name }}</strong><small>{{ $quote->original_name }}</small></div>@if($quote->is_winner)<b>GANADORA</b>@endif</a>@endforeach</div>@if(auth()->user()->isAdministrator())<div class="process-actions"><form method="post" action="{{ route('quotations.destroy',$process) }}" onsubmit="return confirm('¿Eliminar este bloque de cotización y sus archivos?')">@csrf @method('DELETE')<button class="danger">Eliminar</button></form></div>@endif</article>@empty<div class="empty-state"><b>▧</b><p>Aún no se han registrado bloques de cotización.</p></div>@endforelse</div>{{ $processes->links() }}
@endsection
@push('scripts')<script>(()=>{const checks=[...document.querySelectorAll('.quotation-item-check')],all=document.getElementById('select-all-quotation-items'),open=document.getElementById('open-quotation-block'),count=document.getElementById('selected-item-count'),dialog=document.getElementById('quotation-block-dialog'),list=document.getElementById('quotation-selected-items');const sync=()=>{const selected=checks.filter(c=>c.checked);count.textContent=`${selected.length} ítem(s) seleccionados`;open.disabled=!selected.length;all.checked=checks.length>0&&selected.length===checks.length;all.indeterminate=selected.length>0&&!all.checked;document.querySelectorAll('.quotation-requirement-check').forEach(group=>{const groupChecks=checks.filter(c=>c.classList.contains(`requirement-${group.dataset.requirement}`));group.checked=groupChecks.length>0&&groupChecks.every(c=>c.checked);group.indeterminate=groupChecks.some(c=>c.checked)&&!group.checked;});};checks.forEach(c=>c.addEventListener('change',sync));all?.addEventListener('change',()=>{checks.forEach(c=>c.checked=all.checked);sync();});document.querySelectorAll('.quotation-requirement-check').forEach(group=>group.addEventListener('change',()=>{checks.filter(c=>c.classList.contains(`requirement-${group.dataset.requirement}`)).forEach(c=>c.checked=group.checked);sync();}));open?.addEventListener('click',()=>{list.replaceChildren();checks.filter(c=>c.checked).forEach(c=>{const row=c.closest('tr'),item=document.createElement('li');item.textContent=row.querySelector('strong')?.textContent||'Ítem seleccionado';list.appendChild(item);});dialog.showModal();});sync();})();</script>@endpush
