@extends('layouts.app')
@section('title','Productos y Servicios')
@section('content')
<div class="breadcrumb">ALMACÉN › Productos y Servicios</div>
<div class="heading">
    <div><h1>Productos y servicios</h1><p>Administra tu catálogo, precios y niveles de inventario en MySQL.</p></div>
    <div class="heading-actions">
        <button class="secondary" onclick="document.getElementById('product-groups').showModal()">▤ Grupos y subgrupos</button>
        <button class="secondary" onclick="document.getElementById('product-categories').showModal()">▦ Categorías</button>
        <button class="secondary" onclick="document.getElementById('measurement-units').showModal()">◇ Unidades de medida</button>
        <button class="primary" onclick="document.getElementById('new-product').showModal()">＋ Nuevo producto</button>
    </div>
</div>
<div class="stats">
    <article><span>▦</span><div><small>Total de ítems</small><strong>{{ \App\Models\Product::where('is_active',true)->count() }}</strong></div></article>
    <article><span>▣</span><div><small>Productos</small><strong>{{ \App\Models\Product::where('is_active',true)->where('type','Producto')->count() }}</strong></div></article>
    <article><span>◇</span><div><small>Servicios</small><strong>{{ \App\Models\Product::where('is_active',true)->where('type','Servicio')->count() }}</strong></div></article>
    <article><span>!</span><div><small>Stock bajo</small><strong>{{ \App\Models\Product::where('is_active',true)->whereColumn('stock','<=','min_stock')->count() }}</strong></div></article>
</div>
<div class="card">
    <form class="toolbar"><label>⌕ <input name="q" value="{{ request('q') }}" placeholder="Buscar por nombre, código o categoría..."></label><button>Buscar</button></form>
    <div class="table-wrap"><table><thead><tr><th>Producto</th><th>Código</th><th>Categoría</th><th>Unidad</th><th>Stock</th><th>Precio</th><th>IGV</th><th></th></tr></thead><tbody>
    @foreach($products as $product)
        <tr><td><div class="entity"><span>{{ mb_substr($product->name,0,1) }}</span><div><strong>{{ $product->name }}</strong><small>{{ $product->type }}</small></div></div></td><td><code>{{ $product->code }}</code></td><td><em>{{ $product->productGroup?->code ? $product->productGroup->code.' · ' : '' }}{{ $product->productSubgroup?->name ?? $product->category }}</em></td><td>{{ $product->unit }}</td><td>{{ $product->type==='Servicio'?'No aplica':$product->stock }}</td><td><strong>S/ {{ number_format($product->price,2) }}</strong></td><td>{{ $product->includes_tax?'Sí':'No' }}</td><td><div class="row-actions"><button onclick="event.preventDefault();document.getElementById('edit-product-{{ $product->id }}').showModal()">Editar</button>@if(auth()->user()->isAdministrator())<form method="post" action="{{ route('products.destroy',$product) }}" onsubmit="return confirm('¿Eliminar definitivamente este producto o servicio?')">@csrf @method('DELETE')<button class="danger">Eliminar</button></form>@endif</div></td></tr>
        <dialog class="product-dialog" id="edit-product-{{ $product->id }}"><form method="post" action="{{ route('products.update',$product) }}">@csrf @method('PUT')<div class="modal-head product-modal-head"><span class="modal-icon">▣</span><div><h2>Editar producto o servicio</h2><p>Actualiza la información del catálogo.</p></div><button type="button" data-close>×</button></div>@include('products.form',['product'=>$product])<div class="modal-foot"><small>Los campos con * son obligatorios.</small><button type="button" data-close>Cancelar</button><button class="primary">Guardar cambios</button></div></form></dialog>
    @endforeach
    </tbody></table></div>{{ $products->links() }}
</div>

<dialog id="product-categories"><div class="modal-head"><div><h2>Registro de categorías</h2><p>Administra las categorías del catálogo.</p></div><button type="button" data-close>×</button></div>
    <form method="post" action="{{ route('product-categories.store') }}">@csrf<div class="form-grid"><label>Nombre de categoría *<input name="name" required></label><label>Descripción<input name="description"></label></div><div class="modal-foot"><button type="button" data-close>Cancelar</button><button class="primary">＋ Registrar categoría</button></div></form>
    <div class="manage-list">@forelse($categories as $category)<div><span class="entity"><span>{{ mb_substr($category->name,0,1) }}</span><span><strong>{{ $category->name }}</strong><small>{{ $category->description ?: 'Sin descripción' }}</small></span></span><form method="post" action="{{ route('product-categories.destroy',$category) }}">@csrf @method('DELETE')<button class="danger">Retirar</button></form></div>@empty<p>Aún no existen categorías registradas.</p>@endforelse</div>
</dialog>

<dialog id="product-groups" class="product-groups-dialog"><div class="modal-head"><div><h2>Grupos y subgrupos de productos</h2><p>Clasificación por empresa activa. Usa códigos de grupo y subgrupo para ordenar el catálogo.</p></div><button type="button" data-close>×</button></div>
    <div class="group-management-layout"><section><h3>Nuevo grupo</h3><form method="post" action="{{ route('product-groups.store') }}">@csrf<div class="form-grid"><label>Código *<input name="code" maxlength="20" required placeholder="6008"></label><label>Descripción *<input name="name" maxlength="150" required placeholder="SERVICIO DE SUMINISTROS"></label><label>Tipo *<select name="item_type"><option value="Ambos">Producto y servicio</option><option value="Producto">Producto</option><option value="Servicio">Servicio</option></select></label></div><button class="primary">＋ Agregar grupo</button></form></section><section><h3>Nuevo subgrupo</h3><form method="post" action="{{ route('product-subgroups.store') }}">@csrf<div class="form-grid"><label class="span-2">Grupo *<select name="product_group_id" required><option value="">Seleccionar grupo</option>@foreach($groups as $group)<option value="{{ $group->id }}">{{ $group->code }} · {{ $group->name }}</option>@endforeach</select></label><label>Código *<input name="code" maxlength="20" required placeholder="001"></label><label>Descripción *<input name="name" maxlength="150" required placeholder="SUMINISTRO DE ENERGÍA"></label><label>Cuenta<input name="account" maxlength="50"></label><label>Cuenta de existencias<input name="inventory_account" maxlength="50"></label><label>Tipo de gasto<input name="expense_type" maxlength="100"></label></div><button class="primary">＋ Agregar subgrupo</button></form></section></div>
    <div class="group-list"><h3>Estructura registrada</h3>@forelse($groups as $group)<article><header><div><code>{{ $group->code }}</code><strong>{{ $group->name }}</strong><small>{{ $group->item_type }}</small></div>@if(auth()->user()->isAdministrator())<form method="post" action="{{ route('product-groups.destroy',$group) }}" onsubmit="return confirm('¿Eliminar este grupo?')">@csrf @method('DELETE')<button class="danger">Eliminar</button></form>@endif</header><div>@forelse($group->subgroups as $subgroup)<p><code>{{ $subgroup->code }}</code><span>{{ $subgroup->name }}</span><small>{{ $subgroup->account ?: 'Sin cuenta' }}</small>@if(auth()->user()->isAdministrator())<form method="post" action="{{ route('product-subgroups.destroy',$subgroup) }}">@csrf @method('DELETE')<button class="danger">×</button></form>@endif</p>@empty<p class="empty">Sin subgrupos registrados.</p>@endforelse</div></article>@empty<p class="empty-state">No hay grupos registrados para esta empresa.</p>@endforelse</div>
</dialog>

<dialog id="measurement-units"><div class="modal-head"><div><h2>Registro de unidades de medida</h2><p>Administra las unidades disponibles para productos y servicios.</p></div><button type="button" data-close>×</button></div>
    <form method="post" action="{{ route('measurement-units.store') }}">@csrf<div class="form-grid"><label>Nombre de unidad *<input name="name" required placeholder="Ej. Unidad"></label><label>Símbolo *<input name="symbol" required placeholder="Ej. UND"></label></div><div class="modal-foot"><button type="button" data-close>Cancelar</button><button class="primary">＋ Registrar unidad</button></div></form>
    <div class="manage-list">@forelse($units as $unit)<div><span class="entity"><span>{{ mb_substr($unit->symbol,0,1) }}</span><span><strong>{{ $unit->name }}</strong><small>Símbolo: {{ $unit->symbol }}</small></span></span><form method="post" action="{{ route('measurement-units.destroy',$unit) }}">@csrf @method('DELETE')<button class="danger">Retirar</button></form></div>@empty<p>Aún no existen unidades registradas.</p>@endforelse</div>
</dialog>

<dialog class="product-dialog" id="new-product"><form method="post" action="{{ route('products.store') }}">@csrf<div class="modal-head product-modal-head"><span class="modal-icon">▣</span><div><h2>Nuevo producto o servicio</h2><p>Completa la información para agregarlo al catálogo.</p></div><button type="button" data-close>×</button></div>@include('products.form',['product'=>null])<div class="modal-foot"><small>Los campos con * son obligatorios.</small><button type="button" data-close>Cancelar</button><button class="primary">Guardar producto</button></div></form></dialog>
@endsection
@push('scripts')<script>
const productGroups=@json($groupData);
document.querySelectorAll('.product-form').forEach(form=>{const group=form.querySelector('.product-group-select'),subgroup=form.querySelector('.product-subgroup-select'),category=form.querySelector('.product-category-value');const refresh=()=>{const selected=subgroup.dataset.selected;subgroup.innerHTML='<option value="">Sin subgrupo</option>';(productGroups.find(item=>String(item.id)===group.value)?.subgroups||[]).forEach(item=>{const option=new Option(`${item.code} · ${item.name}`,item.id,false,String(item.id)===String(selected));subgroup.add(option);});category.value=subgroup.selectedOptions[0]?.text?.replace(/^.* · /,'')||'';subgroup.dataset.selected='';};const toggleOperation=()=>{const purchase=form.querySelector('[name="operation_type"]:checked')?.value==='Compra';form.querySelectorAll('.sales-only').forEach(field=>{field.hidden=purchase;field.querySelectorAll('input,select').forEach(input=>input.disabled=purchase);});};group.addEventListener('change',refresh);subgroup.addEventListener('change',()=>{category.value=subgroup.selectedOptions[0]?.text?.replace(/^.* · /,'')||'';});form.querySelectorAll('[name="operation_type"]').forEach(input=>input.addEventListener('change',toggleOperation));refresh();toggleOperation();});
</script>@endpush
