@extends('layouts.app')
@section('title','Empresas, Almacenes y Sucursales')
@section('content')
@php
    $branchCount=$companies->sum(fn($company)=>$company->branches->count());
    $warehouseCount=$companies->sum(fn($company)=>$company->branches->sum(fn($branch)=>$branch->warehouses->count()));
@endphp
<div class="breadcrumb">ALMACÉN › Empresas, Almacenes y Sucursales</div>
<div class="heading"><div><h1>Empresas, Almacenes y Sucursales</h1><p>Organiza la estructura logística desde la empresa hasta cada sucursal y sus almacenes.</p></div><div class="heading-actions"><button class="secondary" type="button" onclick="document.getElementById('new-company').showModal()">＋ Nueva empresa</button><button class="primary" type="button" onclick="document.getElementById('new-branch').showModal()">＋ Nueva sucursal</button></div></div>
<div class="stats"><article><span>▣</span><div><small>Empresas</small><strong>{{ $companies->count() }}</strong></div></article><article><span>◇</span><div><small>Sucursales</small><strong>{{ $branchCount }}</strong></div></article><article><span>▦</span><div><small>Almacenes</small><strong>{{ $warehouseCount }}</strong></div></article><article><span>◫</span><div><small>Jerarquía</small><strong>3 niveles</strong></div></article></div>
<div class="company-hierarchy">
@forelse($companies as $company)
<section class="company-node"><header><span>▣</span><div><small>EMPRESA · {{ $company->code }}{{ $company->ruc ? ' · RUC '.$company->ruc : '' }}</small><h2>{{ $company->legal_name ?: $company->name }}</h2><p>{{ $company->branches->count() }} sucursal(es) · {{ $company->branches->sum(fn($branch)=>$branch->warehouses->count()) }} almacén(es)</p></div><button class="secondary" type="button" onclick="openBranch({{ $company->id }}, @js($company->legal_name ?: $company->name))">＋ Agregar sucursal</button></header><div class="company-branches">
@forelse($company->branches as $branch)
<article class="branch-node"><div class="branch-node-head"><span>◇</span><div><strong>{{ $branch->name }}</strong><small>SUCURSAL · {{ $branch->code ?: 'Sin código' }}{{ $branch->address ? ' · '.$branch->address : '' }}</small></div><div class="cost-parent-actions"><button type="button" onclick="openWarehouse({{ $branch->id }}, @js($branch->name), @js($company->name))">＋ Agregar almacén</button>@if(auth()->user()->isAdministrator())<form method="post" action="{{ route('branches.destroy',$branch) }}" onsubmit="return confirm('¿Eliminar definitivamente esta sucursal?')">@csrf @method('delete')<button class="danger-link">Eliminar</button></form>@endif</div></div><div class="warehouse-nodes">@forelse($branch->warehouses as $warehouse)<div class="warehouse-node"><span>└</span><b>▦</b><div><strong>{{ $warehouse->name }}</strong><small>ALMACÉN · {{ $warehouse->code ?: 'Sin código' }}{{ $warehouse->address ? ' · '.$warehouse->address : '' }}</small></div>@if(auth()->user()->isAdministrator())<form method="post" action="{{ route('warehouses.destroy',$warehouse) }}" onsubmit="return confirm('¿Eliminar definitivamente este almacén?')">@csrf @method('delete')<button class="danger-link">Eliminar</button></form>@endif</div>@empty<div class="cost-empty">Esta sucursal todavía no tiene almacenes.</div>@endforelse</div></article>
@empty
<div class="company-empty"><span>◇</span><p>Esta empresa todavía no tiene sucursales.</p><button class="secondary" type="button" onclick="openBranch({{ $company->id }}, @js($company->legal_name ?: $company->name))">Crear primera sucursal</button></div>
@endforelse
</div></section>
@empty
<div class="empty-state"><b>▣</b><p>No hay empresas configuradas.</p></div>
@endforelse
</div>
<dialog id="new-company"><div class="modal-head"><div><h2>Nueva empresa</h2><p>La empresa es el nivel superior de la estructura logística.</p></div><button type="button" data-close>×</button></div><form method="post" action="{{ route('companies.store') }}">@csrf<div class="form-grid"><label>RUC *<input name="ruc" inputmode="numeric" pattern="[0-9]{11}" maxlength="11" required autofocus placeholder="20123456789"></label><label class="span-2">Razón social *<input name="legal_name" maxlength="150" required placeholder="EJ.: COMPAÑÍA MINERA FABULOSA S.A.C."></label><p class="form-help span-2">El código se genera automáticamente con el formato EMP-001. El RUC debe contener 11 dígitos.</p></div><div class="modal-foot"><button type="button" data-close>Cancelar</button><button class="primary">Guardar empresa</button></div></form></dialog>
<dialog id="new-branch"><div class="modal-head"><div><h2>Nueva sucursal</h2><p id="branch-company-label">Selecciona la empresa a la que pertenecerá.</p></div><button type="button" data-close>×</button></div><form method="post" action="{{ route('branches.store') }}">@csrf<div class="form-grid"><label class="span-2">Empresa *<select name="company_id" id="branch-company-id" required><option value="">Seleccionar empresa</option>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name }}</option>@endforeach</select></label><label>Nombre de sucursal *<input name="name" required></label><label class="span-2">Dirección<input name="address"></label></div><div class="modal-foot"><button type="button" data-close>Cancelar</button><button class="primary">Guardar sucursal</button></div></form></dialog>
<dialog id="new-warehouse"><div class="modal-head"><div><h2>Nuevo almacén</h2><p id="warehouse-branch-label"></p></div><button type="button" data-close>×</button></div><form method="post" action="{{ route('warehouses.store') }}">@csrf<input type="hidden" name="branch_id" id="warehouse-branch-id"><div class="form-grid"><label>Nombre del almacén *<input name="name" required></label><label class="span-2">Dirección<input name="address"></label></div><div class="modal-foot"><button type="button" data-close>Cancelar</button><button class="primary">Guardar almacén</button></div></form></dialog>
@endsection
@push('scripts')<script>
const openBranch=(id,name)=>{document.getElementById('branch-company-id').value=id;document.getElementById('branch-company-label').textContent=`La sucursal pertenecerá a: ${name}`;document.getElementById('new-branch').showModal();};
const openWarehouse=(id,branch,company)=>{document.getElementById('warehouse-branch-id').value=id;document.getElementById('warehouse-branch-label').textContent=`Empresa: ${company} · Sucursal: ${branch}`;document.getElementById('new-warehouse').showModal();};
</script>@endpush
