@extends('layouts.app')
@section('title','Almacenes y Sucursales')
@section('content')
<div class="breadcrumb">ALMACÉN › Almacenes y Sucursales</div>
<div class="heading"><div><h1>Almacenes y Sucursales</h1><p>Administra las sucursales principales y los almacenes que dependen de ellas.</p></div><button class="primary" type="button" onclick="document.getElementById('new-branch').showModal()">＋ Nueva sucursal</button></div>
<div class="stats"><article><span>◇</span><div><small>Sucursales</small><strong>{{ $branches->count() }}</strong></div></article><article><span>▦</span><div><small>Almacenes</small><strong>{{ $branches->sum(fn($branch) => $branch->warehouses->count()) }}</strong></div></article><article><span>✓</span><div><small>Disponibles en órdenes</small><strong>{{ $branches->sum(fn($branch) => $branch->warehouses->count()) }}</strong></div></article><article><span>◫</span><div><small>Estructura</small><strong>Padre / hijo</strong></div></article></div>
<div class="card cost-centers-card"><div class="card-title"><div><h2>Estructura logística</h2><p>Selecciona una sucursal para agregarle uno o varios almacenes.</p></div></div><div class="cost-center-tree">@forelse($branches as $branch)<section class="cost-parent"><header><div class="cost-parent-icon">◇</div><div><strong>{{ $branch->name }}</strong><small>{{ $branch->code ?: 'Sin código' }}{{ $branch->address ? ' · '.$branch->address : '' }} · {{ $branch->warehouses->count() }} almacén(es)</small></div><div class="cost-parent-actions"><button type="button" onclick="openWarehouse({{ $branch->id }}, @js($branch->name))">＋ Agregar almacén</button><form method="post" action="{{ route('branches.destroy',$branch) }}" onsubmit="return confirm('¿Retirar la sucursal y sus almacenes?')">@csrf @method('delete')<button class="danger-link">Retirar</button></form></div></header><div class="cost-children">@forelse($branch->warehouses as $warehouse)<div class="cost-child"><span class="cost-branch">└</span><div><strong>{{ $warehouse->name }}</strong><small>{{ $warehouse->code ?: 'Sin código' }}{{ $warehouse->address ? ' · '.$warehouse->address : '' }}</small></div><div class="cost-child-actions"><form method="post" action="{{ route('warehouses.destroy',$warehouse) }}" onsubmit="return confirm('¿Retirar este almacén?')">@csrf @method('delete')<button class="danger-link">Retirar</button></form></div></div>@empty<div class="cost-empty">No hay almacenes en esta sucursal.</div>@endforelse</div></section>@empty<div class="empty-state"><b>◇</b><p>No hay sucursales registradas.</p></div>@endforelse</div></div>
<dialog id="new-branch"><div class="modal-head"><div><h2>Nueva sucursal</h2><p>La sucursal será el nivel padre de los almacenes.</p></div><button type="button" data-close>×</button></div><form method="post" action="{{ route('branches.store') }}">@csrf<div class="form-grid"><label>Nombre *<input name="name" required></label><label>Código<input name="code"></label><label class="span-2">Dirección<input name="address"></label></div><div class="modal-foot"><button type="button" data-close>Cancelar</button><button class="primary">Guardar sucursal</button></div></form></dialog>
<dialog id="new-warehouse"><div class="modal-head"><div><h2>Nuevo almacén</h2><p id="warehouse-branch-label"></p></div><button type="button" data-close>×</button></div><form method="post" action="{{ route('warehouses.store') }}">@csrf<input type="hidden" name="branch_id" id="warehouse-branch-id"><div class="form-grid"><label>Nombre *<input name="name" required></label><label>Código<input name="code"></label><label class="span-2">Dirección<input name="address"></label></div><div class="modal-foot"><button type="button" data-close>Cancelar</button><button class="primary">Guardar almacén</button></div></form></dialog>
@endsection
@push('scripts')<script>const openWarehouse=(id,name)=>{document.getElementById('warehouse-branch-id').value=id;document.getElementById('warehouse-branch-label').textContent=`Se agregará dentro de: ${name}`;document.getElementById('new-warehouse').showModal();};</script>@endpush
