@extends('layouts.app')
@section('title',$form->exists?'Configurar cartilla':'Nueva cartilla')
@section('content')
<form method="post" action="{{ $form->exists ? route('daily-reports.update',$form) : route('daily-reports.store') }}" id="builder-form">@csrf @if($form->exists)@method('PUT')@endif
<div class="daily-builder-head"><a href="{{ route('daily-reports.index') }}">←</a><div><h1>{{ $form->exists?$form->name:'Nueva cartilla digital' }}</h1><span>{{ $form->scope ?: 'Operación general' }}</span></div><div class="builder-actions">@if($form->exists)<a href="{{ route('daily-reports.preview',$form) }}">◉ Previsualizar</a>@endif<button class="primary">{{ $form->exists?'Guardar':'Crear cartilla' }}</button></div></div>
<div class="builder-tabs"><button type="button" class="active" data-tab="questions">PREGUNTAS <b id="field-count">0</b></button><button type="button" data-tab="settings">CONF. CARTILLA</button><button type="button" data-tab="users">USUARIOS</button></div>
<section class="builder-panel active" id="tab-questions">
    <aside class="field-sidebar"><div class="sidebar-title"><strong>Campos de la cartilla</strong><button type="button" id="add-field">＋</button></div><div id="field-list"></div></aside>
    <div class="field-editor"><div class="field-empty" id="field-empty"><b>▤</b><h2>Agrega tu primer campo</h2><p>Incluye fechas, números, opciones, fotos, firmas o fórmulas.</p><button type="button" class="primary" id="empty-add">＋ Agregar campo</button></div><div id="field-editor-content" hidden></div></div>
</section>
<section class="builder-panel" id="tab-settings"><div class="settings-builder-card">
    <div class="builder-basic"><label>Nombre de la cartilla *<input name="name" required value="{{ old('name',$form->name) }}"></label><label>Proyecto / unidad / alcance<input name="scope" value="{{ old('scope',$form->scope) }}" placeholder="Ej. Planta, Mina, Seguridad"></label><label class="full">Descripción<textarea name="description" rows="3">{{ old('description',$form->description) }}</textarea></label></div>
    @foreach(['is_active'=>['Cartilla activa','Permite nuevos registros en esta cartilla.'],'use_gps'=>['Usar geolocalización (GPS)','La ubicación del equipo será obligatoria al guardar.'],'evaluator_location'=>['Ubicación proporcionada por el evaluador','Permite complementar la georreferencia.'],'allow_export'=>['Habilitar exportación de registros','Los responsables podrán exportar la información.'],'exact_search'=>['Búsqueda exacta por texto','La búsqueda utilizará coincidencias exactas.'],'allow_update'=>['Actualizar partes registrados','Autoriza cambios posteriores.'],'auto_collapse'=>['Colapso automático de secciones','Útil en cartillas con muchos campos.']] as $key=>$option)
    <label class="builder-toggle"><input type="checkbox" name="{{ $key }}" value="1" {{ old($key,$form->$key ?? ($key==='is_active'))?'checked':'' }}><span></span><div><strong>{{ $option[0] }}</strong><small>{{ $option[1] }}</small></div></label>
    @endforeach
</div></section>
<section class="builder-panel" id="tab-users"><div class="settings-builder-card"><h2>Usuarios autorizados</h2><p>Selecciona quiénes podrán ver y completar esta cartilla.</p><div class="authorized-users">@foreach($users as $user)<label><input type="checkbox" name="user_ids[]" value="{{ $user->id }}" {{ in_array($user->id,old('user_ids',$form->exists?$form->users->pluck('id')->all():[auth()->id()]))?'checked':'' }}><span>{{ collect(explode(' ',$user->name))->map(fn($w)=>mb_substr($w,0,1))->take(2)->join('') }}</span><div><strong>{{ $user->name }}</strong><small>{{ $user->email }} · {{ $user->profile }}</small></div></label>@endforeach</div></div></section>
</form>
<script type="application/json" id="initial-fields">{!! json_encode(old('fields',$form->exists?$form->fields->map(fn($f)=>['field_key'=>$f->field_key,'section'=>$f->section,'name'=>$f->name,'type'=>$f->type,'help_text'=>$f->help_text,'options'=>implode("\n",$f->options??[]),'formula'=>$f->formula,'is_required'=>$f->is_required,'copy_previous'=>$f->copy_previous])->values():[]), JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>
@endsection
@push('scripts')
<script>
(()=>{const typeLabels={text:'Texto',integer:'Número entero',decimal:'Número decimal',date:'Fecha',time:'Hora',yes_no:'Sí / No',select:'Opciones',multi_select:'Opciones múltiples',photo:'Foto',signature:'Firma',qr:'Código QR',barcode:'Código de barras',formula:'Fórmula',section:'Sección'};let fields=JSON.parse(document.getElementById('initial-fields').textContent||'[]'),selected=fields.length?0:-1;const list=document.getElementById('field-list'),editor=document.getElementById('field-editor-content'),empty=document.getElementById('field-empty');
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function add(){fields.push({field_key:'campo_'+(fields.length+1),section:'Datos generales',name:'Nuevo campo',type:'text',help_text:'',options:'',formula:'',is_required:false,copy_previous:false});selected=fields.length-1;render()}
function render(){document.getElementById('field-count').textContent=fields.length;list.innerHTML=fields.map((f,i)=>`<button type="button" class="${i===selected?'active':''}" data-select="${i}"><span>☷</span><div><strong>${esc(f.name)}</strong><small>${esc(typeLabels[f.type]||f.type)}</small></div><b>✓</b></button>`).join('');empty.hidden=selected>=0;editor.hidden=selected<0;if(selected<0)return;const f=fields[selected];editor.innerHTML=`<div class="field-editor-grid"><label>Nombre<input data-prop="name" value="${esc(f.name)}"></label><label>Tipo<select data-prop="type">${Object.entries(typeLabels).map(([v,l])=>`<option value="${v}" ${f.type===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Sección<input data-prop="section" value="${esc(f.section||'Datos generales')}"></label><label>Identificador para fórmulas<input data-prop="field_key" value="${esc(f.field_key||'')}"></label><label class="full">Texto de ayuda<textarea data-prop="help_text">${esc(f.help_text||'')}</textarea></label>${['select','multi_select'].includes(f.type)?`<label class="full">Opciones (una por línea)<textarea data-prop="options" rows="5">${esc(f.options||'')}</textarea></label>`:''}${f.type==='formula'?`<label class="full">Fórmula <small>Usa identificadores entre llaves, por ejemplo: {horas} * {produccion}</small><input data-prop="formula" value="${esc(f.formula||'')}"></label>`:''}<label class="check-option"><input type="checkbox" data-prop="copy_previous" ${f.copy_previous?'checked':''}> Copiar valor en respuestas consecutivas</label><label class="check-option"><input type="checkbox" data-prop="is_required" ${f.is_required?'checked':''}> Campo requerido</label><button type="button" class="delete-field" id="delete-field">Eliminar campo</button></div>`;bindEditor();}
function bindEditor(){editor.querySelectorAll('[data-prop]').forEach(el=>el.addEventListener('input',()=>{fields[selected][el.dataset.prop]=el.type==='checkbox'?el.checked:el.value;if(['name','type'].includes(el.dataset.prop))render()}));document.getElementById('delete-field').onclick=()=>{fields.splice(selected,1);selected=Math.min(selected,fields.length-1);render()}}
list.addEventListener('click',e=>{const b=e.target.closest('[data-select]');if(b){selected=+b.dataset.select;render()}});document.getElementById('add-field').onclick=add;document.getElementById('empty-add').onclick=add;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.builder-panel').forEach(x=>x.classList.toggle('active',x.id==='tab-'+b.dataset.tab))});document.getElementById('builder-form').addEventListener('submit',e=>{document.querySelectorAll('.generated-field').forEach(x=>x.remove());fields.forEach((f,i)=>Object.entries(f).forEach(([k,v])=>{const x=document.createElement('input');x.type='hidden';x.className='generated-field';x.name=`fields[${i}][${k}]`;x.value=typeof v==='boolean'?(v?'1':'0'):(v??'');e.target.appendChild(x)}));if(!fields.length){e.preventDefault();alert('Agrega al menos un campo a la cartilla.')}});render()})();
</script>
@endpush
