@extends('layouts.app')
@section('title',$form->exists?'Configurar cartilla':'Nueva cartilla')
@section('content')
<form method="post" action="{{ $form->exists ? route('daily-reports.update',$form) : route('daily-reports.store') }}" id="builder-form">@csrf @if($form->exists)@method('PUT')@endif
<div class="daily-builder-head"><a href="{{ route('daily-reports.index') }}">←</a><div class="editable-cartilla-title"><label for="cartilla-name-header">Nombre de la cartilla</label><input id="cartilla-name-header" required value="{{ old('name',$form->name) }}" placeholder="Escriba el nombre de la cartilla"><span>{{ $form->scope ?: 'Operación general' }}</span></div><div class="builder-actions"><button type="button" id="preview-builder">◉ Previsualizar</button><button class="primary">{{ $form->exists?'Guardar':'Crear cartilla' }}</button></div></div>
<div class="builder-tabs"><button type="button" class="active" data-tab="questions">PREGUNTAS <b id="field-count">0</b></button><button type="button" data-tab="settings">CONF. CARTILLA</button><button type="button" data-tab="users">USUARIOS</button></div>
<section class="builder-panel active" id="tab-questions">
    <aside class="field-sidebar"><div class="sidebar-title"><strong>Campos de la cartilla</strong><button type="button" id="add-field">＋</button></div><div id="field-list"></div></aside>
    <div class="field-editor"><div class="field-empty" id="field-empty"><b>▤</b><h2>Agrega tu primer campo</h2><p>Incluye fechas, números, opciones, fotos, firmas o fórmulas.</p><button type="button" class="primary" id="empty-add">＋ Agregar campo</button></div><div id="field-editor-content" hidden></div></div>
</section>
<section class="builder-panel" id="tab-settings"><div class="settings-builder-card">
    <div class="builder-basic"><label>Nombre de la cartilla *<input name="name" id="cartilla-name-settings" required value="{{ old('name',$form->name) }}"></label><label>Proyecto / unidad / alcance<input name="scope" value="{{ old('scope',$form->scope) }}" placeholder="Ej. Planta, Mina, Seguridad"></label><label class="full">Descripción<textarea name="description" rows="3">{{ old('description',$form->description) }}</textarea></label></div>
    @foreach(['is_active'=>['Cartilla activa','Permite nuevos registros en esta cartilla.'],'use_gps'=>['Usar geolocalización (GPS)','La ubicación del equipo será obligatoria al guardar.'],'evaluator_location'=>['Ubicación proporcionada por el evaluador','Permite complementar la georreferencia.'],'allow_export'=>['Habilitar exportación de registros','Los responsables podrán exportar la información.'],'exact_search'=>['Búsqueda exacta por texto','La búsqueda utilizará coincidencias exactas.'],'allow_update'=>['Actualizar partes registrados','Autoriza cambios posteriores.'],'auto_collapse'=>['Colapso automático de secciones','Útil en cartillas con muchos campos.']] as $key=>$option)
    <label class="builder-toggle"><input type="checkbox" name="{{ $key }}" value="1" {{ old($key,$form->$key ?? ($key==='is_active'))?'checked':'' }}><span></span><div><strong>{{ $option[0] }}</strong><small>{{ $option[1] }}</small></div></label>
    @endforeach
</div></section>
<section class="builder-panel" id="tab-users"><div class="settings-builder-card"><h2>Usuarios autorizados</h2><p>Selecciona quiénes podrán ver y completar esta cartilla.</p><div class="authorized-users">@foreach($users as $user)<label><input type="checkbox" name="user_ids[]" value="{{ $user->id }}" {{ in_array($user->id,old('user_ids',$form->exists?$form->users->pluck('id')->all():[auth()->id()]))?'checked':'' }}><span>{{ collect(explode(' ',$user->name))->map(fn($w)=>mb_substr($w,0,1))->take(2)->join('') }}</span><div><strong>{{ $user->name }}</strong><small>{{ $user->email }} · {{ $user->profile }}</small></div></label>@endforeach</div></div></section>
</form>
<dialog id="builder-preview" class="builder-preview-dialog"><div class="preview-dialog-head"><div><h2>Previsualización móvil</h2><p>Así verá el evaluador la cartilla al registrar información.</p></div><button type="button" data-close>×</button></div><div class="phone-stage"><div class="phone-frame"><div class="phone-speaker"></div><div class="phone-screen"><header id="preview-title">CARTILLA DIGITAL</header><div id="preview-fields"></div></div><div class="phone-nav">‹　□　☰</div></div></div></dialog>
<script type="application/json" id="initial-fields">{!! json_encode(old('fields',$form->exists?$form->fields->map(fn($f)=>['field_key'=>$f->field_key,'section'=>$f->section,'name'=>$f->name,'type'=>$f->type,'help_text'=>$f->help_text,'options'=>implode("\n",$f->options??[]),'formula'=>$f->formula,'settings'=>$f->settings??new stdClass(),'is_required'=>$f->is_required,'copy_previous'=>$f->copy_previous])->values():[]), JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>
@endsection
@push('scripts')
<script>
(()=>{const typeLabels={area:'Área de manejo',integer:'Número entero',decimal:'Número decimal',text:'Texto',yes_no:'Sí / No',options:'Opciones',multi_select:'Opciones múltiples',dropdown:'Desplegable',time:'Hora',date:'Fecha',qr:'Código QR',barcode:'Código de barras',photo:'Foto',signature:'Firma',formula:'Fórmula',section:'Sección'};const descriptions={area:'El evaluador seleccionará el área de manejo o podrá determinarla mediante GPS.',integer:'El evaluador ingresará un número entero.',decimal:'El evaluador ingresará un número decimal.',text:'El evaluador ingresará un texto entre los límites establecidos.',yes_no:'El evaluador responderá sí o no.',options:'El evaluador elegirá una opción de una lista siempre visible.',multi_select:'El evaluador podrá elegir varias opciones.',dropdown:'El evaluador buscará y elegirá una opción de una lista desplegable.',time:'El evaluador ingresará una hora.',date:'El evaluador ingresará una fecha.',qr:'El evaluador usará la cámara para leer un código QR.',barcode:'El evaluador usará la cámara para leer un código de barras.',photo:'El evaluador tomará una foto o adjuntará una imagen.',signature:'El evaluador firmará con el dedo o un lápiz táctil.',formula:'El evaluador visualizará un valor calculado automáticamente.',section:'Crea un encabezado para agrupar preguntas.'};let fields=JSON.parse(document.getElementById('initial-fields').textContent||'[]').map(f=>({...f,settings:typeof f.settings==='string'?JSON.parse(f.settings||'{}'):(f.settings||{})})),selected=fields.length?0:-1;const list=document.getElementById('field-list'),editor=document.getElementById('field-editor-content'),empty=document.getElementById('field-empty');
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function add(){fields.push({field_key:'campo_'+(fields.length+1),section:'Datos generales',name:'Nuevo campo',type:'text',help_text:'',options:'',formula:'',settings:{min_chars:0,max_chars:500,content_type:'any'},is_required:false,copy_previous:false});selected=fields.length-1;render()}
function setting(f,key,value=''){return f.settings?.[key]??value}function toggle(key,label,checked,help=''){return `<label class="type-option full"><input type="checkbox" data-setting="${key}" ${checked?'checked':''}><span><strong>${label}</strong>${help?`<small>${help}</small>`:''}</span></label>`}function typeSettings(f){if(f.type==='area')return toggle('allow_geolocation','Permitir geolocalización',setting(f,'allow_geolocation',true),'Usa el GPS para ayudar a determinar el área.')+toggle('auto_locate','Localizar automáticamente',setting(f,'auto_locate',false),'Selecciona automáticamente el área según el GPS.');if(['integer','decimal'].includes(f.type))return toggle('counter_buttons','Botones para conteo',setting(f,'counter_buttons',false),'Agrega botones para aumentar o disminuir el valor.')+toggle('has_limits','Aplicar restricciones',setting(f,'has_limits',false))+`<label>Mínimo<input type="number" step="any" data-setting="min" value="${esc(setting(f,'min',''))}"></label><label>Máximo<input type="number" step="any" data-setting="max" value="${esc(setting(f,'max',''))}"></label>`;if(f.type==='text')return `<label>Mínimo de caracteres<input type="number" min="0" data-setting="min_chars" value="${esc(setting(f,'min_chars',0))}"></label><label>Máximo de caracteres<input type="number" min="1" data-setting="max_chars" value="${esc(setting(f,'max_chars',500))}"></label><label>Tipo de contenido<select data-setting="content_type"><option value="any">Cualquiera</option><option value="letters">Sólo letras</option><option value="numbers">Sólo números</option></select></label>`+toggle('multiline','Varias líneas',setting(f,'multiline',true));if(['options','multi_select','dropdown'].includes(f.type))return `<label class="full">Opciones (una por línea)<textarea data-prop="options" rows="6">${esc(f.options||'')}</textarea></label>`+(f.type==='dropdown'?toggle('dependency','Seleccionar dependencia',setting(f,'dependency',false),'Las opciones podrán depender de otra respuesta.'):'');if(f.type==='formula')return `<label class="full">Fórmula <small>Usa identificadores entre llaves: {toneladas} / {horas}</small><input data-prop="formula" value="${esc(f.formula||'')}"></label><label>Si falta una respuesta<select data-setting="empty_value"><option value="zero">Usar cero</option><option value="empty">Dejar vacío</option></select></label>`;return ''}
function render(){document.getElementById('field-count').textContent=fields.length;list.innerHTML=fields.map((f,i)=>`<button type="button" class="${i===selected?'active':''}" data-select="${i}"><span>${({area:'⌖',integer:'123',decimal:'0.5',yes_no:'☑',options:'◉',multi_select:'☑',dropdown:'▾',time:'◷',date:'▣',qr:'▦',barcode:'▥',photo:'▣',signature:'⌁',formula:'ƒ'})[f.type]||'☷'}</span><div><strong>${esc(f.name)}</strong><small>${esc(typeLabels[f.type]||f.type)}</small></div><b>✓</b></button>`).join('');empty.hidden=selected>=0;editor.hidden=selected<0;if(selected<0)return;const f=fields[selected];f.settings=f.settings||{};editor.innerHTML=`<div class="field-editor-grid"><label>Nombre<input data-prop="name" value="${esc(f.name)}"></label><label>Tipo<select data-prop="type">${Object.entries(typeLabels).map(([v,l])=>`<option value="${v}" ${f.type===v?'selected':''}>${l}</option>`).join('')}</select></label><p class="field-description full">${descriptions[f.type]||''}</p><label>Sección<input data-prop="section" value="${esc(f.section||'Datos generales')}"></label><label>Identificador para fórmulas<input data-prop="field_key" value="${esc(f.field_key||'')}"></label><label class="full">Texto de ayuda<textarea data-prop="help_text">${esc(f.help_text||'')}</textarea></label>${typeSettings(f)}${f.type!=='section'?`<label class="check-option full"><input type="checkbox" data-prop="copy_previous" ${f.copy_previous?'checked':''}> Copiar valor en respuestas consecutivas</label><label class="check-option full"><input type="checkbox" data-prop="is_required" ${f.is_required?'checked':''}> Campo requerido</label>`:''}<button type="button" class="delete-field" id="delete-field">Eliminar campo</button></div>`;const ct=editor.querySelector('[data-setting="content_type"]');if(ct)ct.value=setting(f,'content_type','any');const ev=editor.querySelector('[data-setting="empty_value"]');if(ev)ev.value=setting(f,'empty_value','zero');bindEditor();}
function bindEditor(){editor.querySelectorAll('[data-prop]').forEach(el=>el.addEventListener('input',()=>{fields[selected][el.dataset.prop]=el.type==='checkbox'?el.checked:el.value;if(el.dataset.prop==='name'){const item=list.querySelector(`[data-select="${selected}"] strong`);if(item)item.textContent=el.value||'Sin nombre'}if(el.dataset.prop==='type'){fields[selected].settings={};render()}}));editor.querySelectorAll('[data-setting]').forEach(el=>el.addEventListener('input',()=>{fields[selected].settings[el.dataset.setting]=el.type==='checkbox'?el.checked:el.value}));document.getElementById('delete-field').onclick=()=>{fields.splice(selected,1);selected=Math.min(selected,fields.length-1);render()}}
function previewControl(f){const opts=String(f.options||'').split(/\r?\n/).filter(Boolean);switch(f.type){case'section':return`<h4>${esc(f.name)}</h4>`;case'area':return`<div class="phone-input-row"><select><option>Seleccione área</option></select><button>⌖</button></div>`;case'integer':case'decimal':return f.settings?.counter_buttons?`<div class="phone-counter"><button>−</button><input placeholder="${f.type==='integer'?'Entero':'Decimal'}"><button>＋</button></div>`:`<input placeholder="${f.type==='integer'?'Entero':'Decimal'}">`;case'text':return f.settings?.multiline?'<textarea placeholder="Texto"></textarea>':'<input placeholder="Texto">';case'yes_no':return'<label class="phone-check"><input type="checkbox"> Sí</label>';case'options':return opts.map(o=>`<label class="phone-check"><input type="radio"> ${esc(o)}</label>`).join('');case'multi_select':return opts.map(o=>`<label class="phone-check"><input type="checkbox"> ${esc(o)}</label>`).join('');case'dropdown':return`<select><option>Seleccione una opción</option>${opts.map(o=>`<option>${esc(o)}</option>`).join('')}</select>`;case'time':return'<input type="time">';case'date':return'<input type="date">';case'qr':return'<div class="phone-input-row"><input placeholder="Leer código QR"><button>▦</button></div>';case'barcode':return'<div class="phone-input-row"><input placeholder="Leer código de barras"><button>▥</button></div>';case'photo':return'<button class="phone-action">▣ TOMAR FOTO</button>';case'signature':return'<button class="phone-action">⌁ FIRMAR</button>';case'formula':return'<input readonly placeholder="Cálculo automático">';default:return'<input>'}}
function openPreview(){document.getElementById('preview-title').textContent=(document.getElementById('cartilla-name-header').value||'CARTILLA DIGITAL').toUpperCase();document.getElementById('preview-fields').innerHTML=fields.map(f=>f.type==='section'?previewControl(f):`<div class="phone-field"><label>${esc(f.name)}</label>${previewControl(f)}${f.is_required?'<small>Requerido</small>':''}</div>`).join('')||'<p class="phone-empty">Agrega campos para previsualizar la cartilla.</p>';document.getElementById('builder-preview').showModal()}const headerName=document.getElementById('cartilla-name-header'),settingsName=document.getElementById('cartilla-name-settings');headerName.addEventListener('input',()=>settingsName.value=headerName.value);settingsName.addEventListener('input',()=>headerName.value=settingsName.value);list.addEventListener('click',e=>{const b=e.target.closest('[data-select]');if(b){selected=+b.dataset.select;render()}});document.getElementById('add-field').onclick=add;document.getElementById('empty-add').onclick=add;document.getElementById('preview-builder').onclick=openPreview;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.builder-panel').forEach(x=>x.classList.toggle('active',x.id==='tab-'+b.dataset.tab))});document.getElementById('builder-form').addEventListener('submit',e=>{settingsName.value=headerName.value;document.querySelectorAll('.generated-field').forEach(x=>x.remove());fields.forEach((f,i)=>Object.entries(f).forEach(([k,v])=>{const x=document.createElement('input');x.type='hidden';x.className='generated-field';x.name=`fields[${i}][${k}]`;x.value=k==='settings'?JSON.stringify(v||{}):(typeof v==='boolean'?(v?'1':'0'):(v??''));e.target.appendChild(x)}));if(!fields.length){e.preventDefault();alert('Agrega al menos un campo a la cartilla.')}});render()})();
</script>
@endpush
