plugins { id 'com.android.application' }

android {
    namespace 'com.fabulosa.partediario'
    compileSdk 35

    defaultConfig {
        applicationId 'com.fabulosa.partediario'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.0.2'
        buildConfigField 'String', 'SERVER_URL', '"https://fabulosa.javaltecnologia.es/movil/cartillas"'
    }

    buildFeatures { buildConfig true }
    buildTypes {
        release { minifyEnabled false }
    }
}
